---
- hosts: servers
  gather_facts: yes
  become: true

  tasks:
    - name: Maak tijdelijke map aan in tmp
      action: shell sudo mkdir -p /tmp/nvidia-grid/ && cd /tmp/nvidia-grid/

    - name: Download .run bestand van RCBEHEER1001
      ansible.builtin.get_url:
        url: http://rcbeheer1001/nvidia/NVIDIA-Linux-x86_64-535.161.08-grid.run
        dest: /tmp/nvidia-grid/NVIDIA-Linux-x86_64-535.161.08-grid.run

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /tmp/nvidia-grid/NVIDIA-Linux-x86_64-535.161.08-grid.run
        mode: '0777'
